baseURL = "https://kotanamy.github.io"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "ru"
# language code
languageCode = "ru"
title = "Kotanamy"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "CV"
    pre = ""
    post = ""
    name = "CV"
    url = "cv.pdf"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "Resume"
    pre = ""
    post = ""
    name = "Resume"
    url = ""
    title = ""
    weight = 2

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false