baseURL = "https://kotanamy.github.io"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "ru"
# language code
languageCode = "ru"
title = "Kotanamy"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "RoadToIOS"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "RoadToIOS"
    url = "/posts/"
    # title will be shown when you hover on this menu link.
    title = ""
    weight = 11
  [[menu.main]]
    identifier = "CSharpUnity"
    pre = ""
    post = ""
    name = "CSharpUnity"
    url = "/CSharpUnity/"
    title = ""
    weight = 10
  [[menu.main]]
    identifier = "Other"
    pre = ""
    post = ""
    name = "Other"
    url = "/Other/"
    title = ""
    weight = 12
  [[menu.main]]
    identifier = "CV"
    pre = ""
    post = ""
    name = "CV"
    url = "cv.pdf"
    title = ""
    weight = 13
  [[menu.main]]
    identifier = "Resume"
    pre = ""
    post = ""
    name = "Resume"
    url = ""
    title = ""
    weight = 14

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false